### PR TITLE
Issue #64: Percentage scores now invisible

### PR DESCRIPTION
**Pull request by mjshepherd**

### CODE REVIEW

**Comment by buske** [comment]
Bump.

**Comment by sdumitriu** [comment]
I don't understand this. It seems to be copy/pasted code from `SimilarCases`, and other than a slightly smaller font size and a hardcoded black border, there are no changes. Why?

**Comment by buske** [comment]
@sdumitriu I believe this more tightly constrains the scope of these css definitions, so they don't accidentally affecting those that govern the similarcases variant display.

**Comment by mjshepherd** [comment]
@sdumitriu @buske The code is exactly the same except for a slight difference in size and colour. I wasn't sure what the best practice would be in this case. I didn't have to copy every style, I could have just changed the size and colour in the more specific selector. I duplicated the code because I felt that changes to either the similar cases styles or the top exomiser styles should not effect the appearance of the other.

**Comment by buske** [comment]
Closed in favor of soon-to-be-released variant display widget.

**Pull request closed without merging**
