### PR TITLE
PN-358: Add an info button next to the filtering options under "Matches for patients owned by:"

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by sashaandjic** [comment]
Brittney's suggestions:

**Comment by allasm** [comment]
Has this been discussed? I recall in the past we discussed that users may be confused that some of their matches are not shown (and may not notice this checkbox)

**Comment by sashaandjic** [comment]
Yes, we discussed showing uncontacted matches by default.

**Comment by veronikaslc** [comment]
Removed PN-359 from this PR into separate branch `PN-359`

**Pull request merged**
